# n-body configuration

sherlock:
  env:         '/oak/stanford/orgs/kipac/simpipe'
  systype:     'Generic-gcc'
  commit:      '1e171a4a'
  constraint:  'CLASS:SH3_CBASE'
  taskpernode: 32
  mempernode:  '250G'
  partition:   'kipac'
  acct:        None
s3df:
  env:         '/sdf/group/kipac/simpipe'
  systype:     'Generic-gcc'
  commit:      '1e171a4a'
  constraint:  None
  taskpernode: 120
  mempernode:  '480G'
  partition:   'milano'
  acct:        'kipac'
